name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "13 2 * * *"

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly and run Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_DEEZER_PASSWORD: ${{ secrets.DEEZER_PASSWORD }}]
          CYPRESS_GITHUB_PERSONAL_TOKEN: ${{ secrets.CYPRESS_GITHUB_PERSONAL_TOKEN }}]
